development:
  adapter: postgresql
  encoding: unicode
  database: item_shop_development
  username: postgres
  password: #STUB
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: item_shop_test
  username: postgres
  password: #STUB
  host: localhost
  port: 5432